/**
 * Catálogo de Biomarcadores y presets de estudios de laboratorio clínico (Chopo).
 */

import { BiomarkerCategoryKey, BiomarkerLog, LabTestReport } from "./types";

export interface BiomarkerCategoryMeta {
  key: BiomarkerCategoryKey;
  label: string;
  shortLabel: string;
  icon: string;
  color: string; // Tailwind color token
  description: string;
}

export const BIOMARKER_CATEGORIES_META: Record<BiomarkerCategoryKey, BiomarkerCategoryMeta> = {
  renal: {
    key: "renal",
    label: "Función Renal & Electrolitos",
    shortLabel: "Renal",
    icon: "Activity",
    color: "cyan",
    description: "Filtración glomerular, equilibrio hidroelectrolítico, glucosa y urea.",
  },
  cardio: {
    key: "cardio",
    label: "Riesgo Cardiovascular & Perfil Lipídico",
    shortLabel: "Cardiovascular",
    icon: "Heart",
    color: "rose",
    description: "Colesterol total, HDL, LDL directo, triglicéridos, sd-LDL y PCR ultrasensible.",
  },
  hepatic: {
    key: "hepatic",
    label: "Funcionamiento Hepático & Enzimas",
    shortLabel: "Hepático",
    icon: "Sparkles",
    color: "amber",
    description: "Transaminasas (AST, ALT), GGT, albúmina, fosfatasa alcalina y LDH.",
  },
  iron: {
    key: "iron",
    label: "Metabolismo de Hierro",
    shortLabel: "Hierro",
    icon: "Zap",
    color: "blue",
    description: "Hierro sérico, capacidad de fijación (UIBC, TIBC) y porcentaje de saturación.",
  },
  immuno: {
    key: "immuno",
    label: "Respuesta Inmunológica",
    shortLabel: "Inmunología",
    icon: "Shield",
    color: "indigo",
    description: "Inmunoglobulinas humorales IgG, IgA e IgM en suero.",
  },
  hematology: {
    key: "hematology",
    label: "Biometría Hemática Completa",
    shortLabel: "Hematología",
    icon: "Droplet",
    color: "red",
    description: "Serie roja (hemoglobina, hematócrito, eritrocitos), plaquetas y serie blanca diferencial.",
  },
  urinalysis: {
    key: "urinalysis",
    label: "Examen General de Orina (EGO)",
    shortLabel: "Orina (EGO)",
    icon: "FlaskConical",
    color: "yellow",
    description: "Parámetros físicos, químicos y sedimento microscópico.",
  },
};

/**
 * Estudio Clínico Inicial: Alejandro Bautista Arellano
 * Laboratorio Chopo - 07/02/2026 - Orden: A01510965
 */
export const INITIAL_CHOPO_2026_BIOMARKERS: BiomarkerLog[] = [
  // 1. RENAL & METABÓLICO
  {
    id: "bio-glucosa-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Glucosa en Suero",
    code: "GLU",
    valueNumeric: 83,
    unit: "mg/dL",
    refMin: 55,
    refMax: 99,
    refText: "55 - 99 mg/dL",
    status: "optimal",
    notes: "Nivel de glucosa basal en ayuno óptimo y sensible a la insulina.",
    orderIndex: 1,
  },
  {
    id: "bio-bun-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Nitrógeno de Urea (BUN)",
    code: "BUN",
    valueNumeric: 12.0,
    unit: "mg/dL",
    refMin: 6.5,
    refMax: 23.4,
    refText: "6.5 - 23.4 mg/dL",
    status: "optimal",
    notes: "Buen balance nitrogenado y filtración adecuada.",
    orderIndex: 2,
  },
  {
    id: "bio-urea-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Urea",
    code: "UREA",
    valueNumeric: 25,
    unit: "mg/dL",
    refMin: 14,
    refMax: 50,
    refText: "14 - 50 mg/dL",
    status: "optimal",
    notes: "Metabolismo proteico en equilibrio.",
    orderIndex: 3,
  },
  {
    id: "bio-creat-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Creatinina Sérica",
    code: "CREAT",
    valueNumeric: 0.90,
    unit: "mg/dL",
    refMin: 0.70,
    refMax: 1.20,
    refText: "0.70 - 1.20 mg/dL",
    status: "optimal",
    notes: "Excelente para un deportista con suplementación de creatina.",
    orderIndex: 4,
  },
  {
    id: "bio-bun-creat-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Relación BUN / Creatinina",
    code: "BUN_CREAT",
    valueNumeric: 13,
    unit: "ratio",
    refMin: 9.3,
    refMax: 19.5,
    refText: "9.3 - 19.5",
    status: "optimal",
    notes: "Proporción equilibrada sin datos de deshidratación severa ni patología pre-renal.",
    orderIndex: 5,
  },
  {
    id: "bio-acido-urico-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Ácido Úrico",
    code: "URIC",
    valueNumeric: 5.5,
    unit: "mg/dL",
    refMin: 3.4,
    refMax: 7.0,
    refText: "3.4 - 7.0 mg/dL",
    status: "optimal",
    notes: "Eliminación de purinas en rango normal.",
    orderIndex: 6,
  },
  {
    id: "bio-fosforo-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Fósforo Sérico",
    code: "P",
    valueNumeric: 4.8,
    unit: "mg/dL",
    refMin: 2.5,
    refMax: 4.5,
    refText: "2.5 - 4.5 mg/dL",
    status: "high",
    notes: "Ligeramente por encima del rango superior (4.8 vs 4.5). Monitorear ingesta de semillas/granos o lácteos.",
    orderIndex: 7,
  },
  {
    id: "bio-calcio-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Calcio Sérico",
    code: "CA",
    valueNumeric: 9.7,
    unit: "mg/dL",
    refMin: 8.6,
    refMax: 10.0,
    refText: "8.6 - 10.0 mg/dL",
    status: "optimal",
    notes: "Homeostasis de calcio adecuada.",
    orderIndex: 8,
  },
  {
    id: "bio-magnesio-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Magnesio Sérico",
    code: "MG",
    valueNumeric: 2.3,
    unit: "mg/dL",
    refMin: 1.6,
    refMax: 2.6,
    refText: "1.6 - 2.6 mg/dL",
    status: "optimal",
    notes: "Niveles neuromusculares óptimos.",
    orderIndex: 9,
  },
  {
    id: "bio-sodio-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Sodio Sérico",
    code: "NA",
    valueNumeric: 145,
    unit: "meq/L",
    refMin: 136,
    refMax: 145,
    refText: "136 - 145 meq/L",
    status: "normal",
    notes: "Límite superior normal. Mantener la meta de 3L de agua diaria.",
    orderIndex: 10,
  },
  {
    id: "bio-potasio-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Potasio Sérico",
    code: "K",
    valueNumeric: 4.6,
    unit: "meq/L",
    refMin: 3.5,
    refMax: 5.1,
    refText: "3.5 - 5.1 meq/L",
    status: "optimal",
    notes: "Excelente equilibrio hidroelectrolítico y función muscular.",
    orderIndex: 11,
  },
  {
    id: "bio-cloro-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Cloro Sérico",
    code: "CL",
    valueNumeric: 105,
    unit: "meq/L",
    refMin: 99,
    refMax: 109,
    refText: "99 - 109 meq/L",
    status: "optimal",
    notes: "En rango medio ideal.",
    orderIndex: 12,
  },
  {
    id: "bio-tfge-2026-02-07",
    date: "2026-02-07",
    category: "renal",
    name: "Tasa Filtración Glomerular (TFGe CKD-EPI)",
    code: "TFGE",
    valueNumeric: 120.8,
    unit: "mL/min/1.73m²",
    refMin: 90,
    refMax: 150,
    refText: "> 60 mL/min/1.73m² (>90 Estadio G1)",
    status: "optimal",
    notes: "Estadio G1: Función renal sobresaliente y óptima.",
    orderIndex: 13,
  },

  // 2. RIESGO CARDIOVASCULAR & PERFIL LIPÍDICO
  {
    id: "bio-colest-tot-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Colesterol Total",
    code: "CHOL",
    valueNumeric: 154,
    unit: "mg/dL",
    refMin: 100,
    refMax: 200,
    refText: "< 200 mg/dL (Deseable)",
    status: "optimal",
    notes: "Nivel deseable muy favorable.",
    orderIndex: 14,
  },
  {
    id: "bio-hdl-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Colesterol HDL (Bueno)",
    code: "HDL",
    valueNumeric: 40,
    unit: "mg/dL",
    refMin: 40,
    refMax: 60,
    refText: "40 - 60 mg/dL",
    status: "normal",
    notes: "En rango basal. El cardio regular y grasas saludables (Omega 3, aguacate, oliva) ayudan a elevarlo.",
    orderIndex: 15,
  },
  {
    id: "bio-ldl-dir-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Colesterol LDL Directo",
    code: "LDL_DIR",
    valueNumeric: 97,
    unit: "mg/dL",
    refMin: 0,
    refMax: 100,
    refText: "< 100 mg/dL (Óptimo)",
    status: "optimal",
    notes: "Dentro del rango óptimo preventivo.",
    orderIndex: 16,
  },
  {
    id: "bio-triglic-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Triglicéridos",
    code: "TRIG",
    valueNumeric: 88,
    unit: "mg/dL",
    refMin: 0,
    refMax: 150,
    refText: "< 150 mg/dL (Normal)",
    status: "optimal",
    notes: "Excelente control lipídico, muy por debajo del límite de 150.",
    orderIndex: 17,
  },
  {
    id: "bio-no-hdl-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Colesterol No-HDL",
    code: "NOHDL",
    valueNumeric: 114,
    unit: "mg/dL",
    refMin: 0,
    refMax: 130,
    refText: "< 130 mg/dL (Óptimo)",
    status: "optimal",
    notes: "Perfil aterogénico global bajo.",
    orderIndex: 18,
  },
  {
    id: "bio-indice-ater-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Índice Aterogénico (Col/HDL)",
    code: "ATHERO_IDX",
    valueNumeric: 3.9,
    unit: "ratio",
    refMin: 0,
    refMax: 4.5,
    refText: "< 4.5 (Óptimo)",
    status: "optimal",
    notes: "Riesgo cardiovascular bajo.",
    orderIndex: 19,
  },
  {
    id: "bio-rel-ldl-hdl-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Relación LDL / HDL",
    code: "LDL_HDL",
    valueNumeric: 2.4,
    unit: "ratio",
    refMin: 0,
    refMax: 3.0,
    refText: "< 3.0 (Riesgo bajo)",
    status: "optimal",
    notes: "Excelente equilibrio.",
    orderIndex: 20,
  },
  {
    id: "bio-sd-ldl-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "sd-LDL (LDL Pequeño y Denso)",
    code: "SD_LDL",
    valueNumeric: 2.20,
    unit: "mg/dL",
    refMin: 0,
    refMax: 1.35,
    refText: "0 - 1.35",
    status: "high",
    notes: "Fracción densa de LDL por encima de 1.35. Foco en dieta antiinflamatoria rica en polifenoles y fibra.",
    orderIndex: 21,
  },
  {
    id: "bio-vldl-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "VLDL Colesterol",
    code: "VLDL",
    valueNumeric: 17,
    unit: "mg/dL",
    refMin: 0,
    refMax: 35,
    refText: "< 35 mg/dL",
    status: "optimal",
    notes: "Nivel muy bajo y saludable.",
    orderIndex: 22,
  },
  {
    id: "bio-lipidos-tot-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Lípidos Totales",
    code: "TOTAL_LIPIDS",
    valueNumeric: 404,
    unit: "mg/dL",
    refMin: 380,
    refMax: 748,
    refText: "380 - 748 mg/dL",
    status: "normal",
    notes: "Balance lipídico total normal.",
    orderIndex: 23,
  },
  {
    id: "bio-fosfolipidos-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Fosfolípidos en Suero",
    code: "PHOSPHOLIPIDS",
    valueNumeric: 179,
    unit: "mg/dL",
    refMin: 161,
    refMax: 265,
    refText: "161 - 265 mg/dL",
    status: "optimal",
    notes: "Integridad de membranas celulares correcta.",
    orderIndex: 24,
  },
  {
    id: "bio-pcr-us-2026-02-07",
    date: "2026-02-07",
    category: "cardio",
    name: "Proteína C Reactiva Ultrasensible (PCR-us)",
    code: "HS_CRP",
    valueNumeric: 0.130,
    unit: "mg/dL",
    refMin: 0,
    refMax: 0.50,
    refText: "< 0.5 mg/dL (< 0.1 Bajo, 0.1-0.3 Promedio)",
    status: "normal",
    notes: "Inflamación sistémica vascular baja/controlada según CDC/AHA.",
    orderIndex: 25,
  },

  // 3. FUNCIONAMIENTO HEPÁTICO
  {
    id: "bio-bili-tot-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Bilirrubina Total",
    code: "TBIL",
    valueNumeric: 0.47,
    unit: "mg/dL",
    refMin: 0.1,
    refMax: 1.2,
    refText: "< 1.2 mg/dL",
    status: "optimal",
    notes: "Excelente conjugación y depuración biliar.",
    orderIndex: 26,
  },
  {
    id: "bio-bili-dir-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Bilirrubina Directa",
    code: "DBIL",
    valueNumeric: 0.13,
    unit: "mg/dL",
    refMin: 0.09,
    refMax: 0.30,
    refText: "0.09 - 0.30 mg/dL",
    status: "optimal",
    notes: "En rango óptimo.",
    orderIndex: 27,
  },
  {
    id: "bio-bili-indir-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Bilirrubina Indirecta",
    code: "IBIL",
    valueNumeric: 0.34,
    unit: "mg/dL",
    refMin: 0.01,
    refMax: 0.90,
    refText: "0.01 - 0.90 mg/dL",
    status: "optimal",
    notes: "Hemólisis y reciclaje normal.",
    orderIndex: 28,
  },
  {
    id: "bio-ast-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "AST (TGO)",
    code: "AST",
    valueNumeric: 29,
    unit: "U/L",
    refMin: 10,
    refMax: 39,
    refText: "< 39 U/L",
    status: "optimal",
    notes: "Enzima intracelular hepática/muscular en rango normal.",
    orderIndex: 29,
  },
  {
    id: "bio-alt-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "ALT (TGP)",
    code: "ALT",
    valueNumeric: 37,
    unit: "U/L",
    refMin: 10,
    refMax: 61,
    refText: "< 61 U/L",
    status: "optimal",
    notes: "Enzima específica hepatocelular completamente saludable.",
    orderIndex: 30,
  },
  {
    id: "bio-rel-ast-alt-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Relación AST / ALT",
    code: "AST_ALT",
    valueNumeric: 0.8,
    unit: "ratio",
    refMin: 0,
    refMax: 2.0,
    refText: "< 2.0",
    status: "optimal",
    notes: "Transaminasas normales.",
    orderIndex: 31,
  },
  {
    id: "bio-ggt-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Gama Glutamil Transpeptidasa (GGT)",
    code: "GGT",
    valueNumeric: 18,
    unit: "U/L",
    refMin: 8,
    refMax: 61,
    refText: "8 - 61 U/L",
    status: "optimal",
    notes: "Vía biliar e hígado sin estrés oxidativo por fármacos o alcohol.",
    orderIndex: 32,
  },
  {
    id: "bio-prot-tot-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Proteínas Totales",
    code: "TP",
    valueNumeric: 7.8,
    unit: "g/dL",
    refMin: 6.3,
    refMax: 8.1,
    refText: "6.3 - 8.1 g/dL",
    status: "optimal",
    notes: "Excelente síntesis proteica hepática.",
    orderIndex: 33,
  },
  {
    id: "bio-albumina-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Albúmina",
    code: "ALB",
    valueNumeric: 5.2,
    unit: "g/dL",
    refMin: 3.9,
    refMax: 5.1,
    refText: "3.9 - 5.1 g/dL",
    status: "high",
    notes: "Ligeramente elevada (5.2 vs 5.1), habitual con dieta alta en proteína y ligera hemoconcentración pre-estudio.",
    orderIndex: 34,
  },
  {
    id: "bio-globulinas-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Globulinas",
    code: "GLOB",
    valueNumeric: 2.6,
    unit: "g/dL",
    refMin: 2.4,
    refMax: 3.0,
    refText: "2.4 - 3.0 g/dL",
    status: "optimal",
    notes: "Proteínas inmunes en rango normal.",
    orderIndex: 35,
  },
  {
    id: "bio-rel-ag-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Relación Albúmina / Globulina (A/G)",
    code: "AG_RATIO",
    valueNumeric: 1.96,
    unit: "ratio",
    refMin: 1.18,
    refMax: 2.33,
    refText: "1.18 - 2.33",
    status: "optimal",
    notes: "Proporción armónica de proteínas plasmáticas.",
    orderIndex: 36,
  },
  {
    id: "bio-alp-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Fosfatasa Alcalina Total (FA)",
    code: "ALP",
    valueNumeric: 137,
    unit: "U/L",
    refMin: 45,
    refMax: 128,
    refText: "45 - 128 U/L",
    status: "high",
    notes: "Discretamente sobre el rango (137 vs 128). Frecuente en hombres jóvenes de 22 años con alto recambio óseo y muscular.",
    orderIndex: 37,
  },
  {
    id: "bio-ldh-2026-02-07",
    date: "2026-02-07",
    category: "hepatic",
    name: "Deshidrogenasa Láctica (LDH)",
    code: "LDH",
    valueNumeric: 287,
    unit: "U/L",
    refMin: 125,
    refMax: 239,
    refText: "125 - 239 U/L",
    status: "high",
    notes: "Elevación moderada (287 vs 239), clásico marcador de adaptación y microdaño muscular tras entrenamientos intensos en Hevy/Gym.",
    orderIndex: 38,
  },

  // 4. METABOLISMO DE HIERRO
  {
    id: "bio-hierro-2026-02-07",
    date: "2026-02-07",
    category: "iron",
    name: "Hierro Sérico",
    code: "FE",
    valueNumeric: 101,
    unit: "µg/dL",
    refMin: 33,
    refMax: 193,
    refText: "33 - 193 µg/dL",
    status: "optimal",
    notes: "Depósitos circulantes de hierro ideales.",
    orderIndex: 39,
  },
  {
    id: "bio-uibc-2026-02-07",
    date: "2026-02-07",
    category: "iron",
    name: "UIBC (Capacidad No Saturada de Fijación)",
    code: "UIBC",
    valueNumeric: 244,
    unit: "µg/dL",
    refMin: 125,
    refMax: 345,
    refText: "125 - 345 µg/dL",
    status: "optimal",
    notes: "Capacidad de transporte disponible adecuada.",
    orderIndex: 40,
  },
  {
    id: "bio-tibc-2026-02-07",
    date: "2026-02-07",
    category: "iron",
    name: "Captación Total de Hierro (TIBC)",
    code: "TIBC",
    valueNumeric: 345,
    unit: "µg/dL",
    refMin: 250,
    refMax: 450,
    refText: "250 - 450 µg/dL",
    status: "optimal",
    notes: "Transporte de transferrina en equilibrio.",
    orderIndex: 41,
  },
  {
    id: "bio-sat-hierro-2026-02-07",
    date: "2026-02-07",
    category: "iron",
    name: "Porcentaje de Saturación de Hierro",
    code: "FE_SAT",
    valueNumeric: 29,
    unit: "%",
    refMin: 15,
    refMax: 50,
    refText: "15 - 50 %",
    status: "optimal",
    notes: "Porcentaje de saturación perfecto para oxigenación tisular y síntesis de glóbulos rojos.",
    orderIndex: 42,
  },

  // 5. RESPUESTA INMUNOLÓGICA
  {
    id: "bio-igg-2026-02-07",
    date: "2026-02-07",
    category: "immuno",
    name: "Inmunoglobulina G (IgG)",
    code: "IGG",
    valueNumeric: 1444,
    unit: "mg/dL",
    refMin: 700,
    refMax: 1600,
    refText: "700 - 1600 mg/dL",
    status: "optimal",
    notes: "Inmunidad humoral de memoria sólida y robusta.",
    orderIndex: 43,
  },
  {
    id: "bio-iga-2026-02-07",
    date: "2026-02-07",
    category: "immuno",
    name: "Inmunoglobulina A (IgA)",
    code: "IGA",
    valueNumeric: 213,
    unit: "mg/dL",
    refMin: 70,
    refMax: 400,
    refText: "70 - 400 mg/dL",
    status: "optimal",
    notes: "Inmunidad de mucosas respiratorias y gastrointestinales sana.",
    orderIndex: 44,
  },
  {
    id: "bio-igm-2026-02-07",
    date: "2026-02-07",
    category: "immuno",
    name: "Inmunoglobulina M (IgM)",
    code: "IGM",
    valueNumeric: 43,
    unit: "mg/dL",
    refMin: 40,
    refMax: 230,
    refText: "40 - 230 mg/dL",
    status: "normal",
    notes: "Sin respuesta a infección aguda reciente.",
    orderIndex: 45,
  },

  // 6. BIOMETRÍA HEMÁTICA COMPLETA
  {
    id: "bio-leuco-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Leucocitos Totales (Glóbulos Blancos)",
    code: "WBC",
    valueNumeric: 6.31,
    unit: "miles/µL",
    refMin: 3.8,
    refMax: 11.6,
    refText: "3.8 - 11.6 miles/µL",
    status: "optimal",
    notes: "Conteo leucocitario balanceado.",
    orderIndex: 46,
  },
  {
    id: "bio-erito-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Eritrocitos (Glóbulos Rojos)",
    code: "RBC",
    valueNumeric: 5.95,
    unit: "millones/µL",
    refMin: 4.70,
    refMax: 5.80,
    refText: "4.70 - 5.80 millones/µL",
    status: "high",
    notes: "Ligeramente por encima de 5.80. Adaptación fisiológica a entrenamiento de fuerza y altitud en CDMX.",
    orderIndex: 47,
  },
  {
    id: "bio-hb-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Hemoglobina",
    code: "HGB",
    valueNumeric: 19.1,
    unit: "g/dL",
    refMin: 14.0,
    refMax: 18.0,
    refText: "14.0 - 18.0 g/dL",
    status: "high",
    notes: "19.1 g/dL. Excelente capacidad de transporte de oxígeno. Mantener hidratación continua (>3L/día).",
    orderIndex: 48,
  },
  {
    id: "bio-hto-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Hematócrito",
    code: "HCT",
    valueNumeric: 56.7,
    unit: "%",
    refMin: 40.0,
    refMax: 54.0,
    refText: "40.0 - 54.0 %",
    status: "high",
    notes: "56.7%. Poliglobulia fisiológica por entrenamiento y altitud geográfica.",
    orderIndex: 49,
  },
  {
    id: "bio-vcm-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Volumen Corpuscular Medio (VCM)",
    code: "MCV",
    valueNumeric: 95.3,
    unit: "fL",
    refMin: 78.0,
    refMax: 99.0,
    refText: "78.0 - 99.0 fL",
    status: "optimal",
    notes: "Tamaño eritrocitario normocítico perfecto (descarta deficiencias de B12/folato y microcitosis).",
    orderIndex: 50,
  },
  {
    id: "bio-hcm-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Hemoglobina Corpuscular Media (HCM)",
    code: "MCH",
    valueNumeric: 32.1,
    unit: "pg",
    refMin: 27.0,
    refMax: 31.0,
    refText: "27.0 - 31.0 pg",
    status: "high",
    notes: "Ligeramente por encima (32.1 vs 31.0), congruente con alta hemoglobina.",
    orderIndex: 51,
  },
  {
    id: "bio-cmhc-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Conc. Media Hemoglobina Corp. (CMHC)",
    code: "MCHC",
    valueNumeric: 33.7,
    unit: "g/dL",
    refMin: 32.0,
    refMax: 36.0,
    refText: "32.0 - 36.0 g/dL",
    status: "optimal",
    notes: "Normocrómica adecuada.",
    orderIndex: 52,
  },
  {
    id: "bio-rdw-cv-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Ancho Distrib. Eritrocitos (RDW-CV)",
    code: "RDW_CV",
    valueNumeric: 12.1,
    unit: "%",
    refMin: 11.5,
    refMax: 17.0,
    refText: "11.5 - 17.0 %",
    status: "optimal",
    notes: "Uniformidad eritrocitaria excelente (sin anisocitosis).",
    orderIndex: 53,
  },
  {
    id: "bio-plaquetas-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Plaquetas",
    code: "PLT",
    valueNumeric: 228,
    unit: "miles/µL",
    refMin: 150,
    refMax: 500,
    refText: "150 - 500 miles/µL",
    status: "optimal",
    notes: "Conteo plaquetario ideal para coagulación y recuperación.",
    orderIndex: 54,
  },
  {
    id: "bio-vpm-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Volumen Plaquetario Medio (VPM)",
    code: "MPV",
    valueNumeric: 11.3,
    unit: "fL",
    refMin: 9.6,
    refMax: 13.4,
    refText: "9.6 - 13.4 fL",
    status: "optimal",
    notes: "Maduración plaquetaria normal.",
    orderIndex: 55,
  },
  {
    id: "bio-neutro-pct-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Neutrófilos Relativos (%)",
    code: "NEUT_PCT",
    valueNumeric: 36.1,
    unit: "%",
    refMin: 38.4,
    refMax: 74.6,
    refText: "38.4 - 74.6 %",
    status: "low",
    notes: "Porcentaje relativo ligeramente bajo (36.1%), pero su conteo absoluto (2.28 miles/µL) es 100% normal.",
    orderIndex: 56,
  },
  {
    id: "bio-linfo-pct-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Linfocitos Relativos (%)",
    code: "LYMPH_PCT",
    valueNumeric: 47.7,
    unit: "%",
    refMin: 16.5,
    refMax: 49.6,
    refText: "16.5 - 49.6 %",
    status: "optimal",
    notes: "En rango normal alto.",
    orderIndex: 57,
  },
  {
    id: "bio-mono-pct-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Monocitos Relativos (%)",
    code: "MONO_PCT",
    valueNumeric: 12.0,
    unit: "%",
    refMin: 4.6,
    refMax: 12.7,
    refText: "4.6 - 12.7 %",
    status: "optimal",
    notes: "En rango normal.",
    orderIndex: 58,
  },
  {
    id: "bio-eos-pct-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Eosinófilos Relativos (%)",
    code: "EOS_PCT",
    valueNumeric: 3.2,
    unit: "%",
    refMin: 1.0,
    refMax: 4.0,
    refText: "1.0 - 4.0 %",
    status: "optimal",
    notes: "Sin datos de alergia ni parasitosis.",
    orderIndex: 59,
  },
  {
    id: "bio-baso-pct-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Basófilos Relativos (%)",
    code: "BASO_PCT",
    valueNumeric: 1.0,
    unit: "%",
    refMin: 0.0,
    refMax: 1.0,
    refText: "0.0 - 1.0 %",
    status: "normal",
    notes: "En rango normal.",
    orderIndex: 60,
  },
  {
    id: "bio-neutro-abs-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Neutrófilos Absolutos",
    code: "NEUT_ABS",
    valueNumeric: 2.28,
    unit: "miles/µL",
    refMin: 1.69,
    refMax: 7.16,
    refText: "1.69 - 7.16 miles/µL",
    status: "optimal",
    notes: "Conteo absoluto completamente sano.",
    orderIndex: 61,
  },
  {
    id: "bio-linfo-abs-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Linfocitos Absolutos",
    code: "LYMPH_ABS",
    valueNumeric: 3.01,
    unit: "miles/µL",
    refMin: 1.05,
    refMax: 3.53,
    refText: "1.05 - 3.53 miles/µL",
    status: "optimal",
    notes: "Conteo absoluto completamente sano.",
    orderIndex: 62,
  },
  {
    id: "bio-mono-abs-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Monocitos Absolutos",
    code: "MONO_ABS",
    valueNumeric: 0.76,
    unit: "miles/µL",
    refMin: 0.25,
    refMax: 0.90,
    refText: "0.25 - 0.90 miles/µL",
    status: "optimal",
    notes: "Conteo absoluto completamente sano.",
    orderIndex: 63,
  },
  {
    id: "bio-eos-abs-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Eosinófilos Absolutos",
    code: "EOS_ABS",
    valueNumeric: 0.20,
    unit: "miles/µL",
    refMin: 0.02,
    refMax: 0.50,
    refText: "0.02 - 0.50 miles/µL",
    status: "optimal",
    notes: "En rango normal.",
    orderIndex: 64,
  },
  {
    id: "bio-baso-abs-2026-02-07",
    date: "2026-02-07",
    category: "hematology",
    name: "Basófilos Absolutos",
    code: "BASO_ABS",
    valueNumeric: 0.06,
    unit: "miles/µL",
    refMin: 0.01,
    refMax: 0.10,
    refText: "0.01 - 0.10 miles/µL",
    status: "optimal",
    notes: "En rango normal.",
    orderIndex: 65,
  },

  // 7. EXAMEN GENERAL DE ORINA (EGO)
  {
    id: "bio-ego-densidad-2026-02-07",
    date: "2026-02-07",
    category: "urinalysis",
    name: "Densidad Urinaria",
    code: "URINE_SG",
    valueNumeric: 1.014,
    unit: "SG",
    refMin: 1.005,
    refMax: 1.030,
    refText: "1.005 - 1.030",
    status: "optimal",
    notes: "Densidad urinaria ideal y excelente capacidad de concentración/dilución renal.",
    orderIndex: 66,
  },
  {
    id: "bio-ego-ph-2026-02-07",
    date: "2026-02-07",
    category: "urinalysis",
    name: "pH Urinario",
    code: "URINE_PH",
    valueNumeric: 6.0,
    unit: "pH",
    refMin: 4.8,
    refMax: 7.4,
    refText: "4.8 - 7.4",
    status: "optimal",
    notes: "pH fisiológico perfectamente balanceado.",
    orderIndex: 67,
  },
  {
    id: "bio-ego-aspecto-2026-02-07",
    date: "2026-02-07",
    category: "urinalysis",
    name: "Aspecto & Color",
    code: "URINE_PHYS",
    valueText: "Amarillo Claro",
    status: "optimal",
    notes: "Color amarillo, aspecto claro y transparente.",
    orderIndex: 68,
  },
  {
    id: "bio-ego-quimico-2026-02-07",
    date: "2026-02-07",
    category: "urinalysis",
    name: "Química Urinaria (Proteínas, Glucosa, Cetonas)",
    code: "URINE_CHEM",
    valueText: "100% Negativo",
    refText: "Negativo",
    status: "optimal",
    notes: "Proteínas, glucosa, cetonas, nitritos, bilirrubina y hemoglobina todos negativos.",
    orderIndex: 69,
  },
  {
    id: "bio-ego-micro-2026-02-07",
    date: "2026-02-07",
    category: "urinalysis",
    name: "Sedimento Microscópico",
    code: "URINE_MICRO",
    valueText: "Ausentes / Limpio",
    refText: "Ausentes",
    status: "optimal",
    notes: "Leucocitos, eritrocitos, cilindros, cristales, bacterias y levaduras ausentes. Muestra limpia.",
    orderIndex: 70,
  },
];

export const INITIAL_CHOPO_2026_REPORT: LabTestReport = {
  id: "chopo-2026-02-07-A01510965",
  date: "2026-02-07",
  labName: "Laboratorio Chopo (Sucursal Santa María)",
  orderNumber: "A01510965",
  patientId: "26772693",
  title: "Química Integral de 45 Elementos, Biometría Hemática y EGO",
  doctorNotes: "Paciente masculino de 22 años. Excelente estado metabólico general y filtración renal (TFGe 120.8). Serie roja elevada congruente con entrenamiento y altitud.",
  totalBiomarkers: INITIAL_CHOPO_2026_BIOMARKERS.length,
  abnormalCount: INITIAL_CHOPO_2026_BIOMARKERS.filter(
    (b) => b.status === "high" || b.status === "low" || b.status === "critical"
  ).length,
  biomarkers: INITIAL_CHOPO_2026_BIOMARKERS,
  createdAt: "2026-02-07T09:44:16Z",
};
